# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r7D5sNROqjPtUp9mH9U0Zp9310kY7aEZ
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from imblearn.over_sampling import SMOTE, RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTETomek

df = pd.read_csv("Creditcard_data.csv")

X = df.drop("Class", axis=1)
y = df["Class"]

models = {
    "M1_LogisticRegression": LogisticRegression(max_iter=1000),
    "M2_DecisionTree": DecisionTreeClassifier(),
    "M3_RandomForest": RandomForestClassifier(),
    "M4_NaiveBayes": GaussianNB(),
    "M5_SVM": SVC()
}

sampling_methods = {
    "Sampling1_RandomOver": RandomOverSampler(),
    "Sampling2_SMOTE": SMOTE(),
    "Sampling3_RandomUnder": RandomUnderSampler(),
    "Sampling4_SMOTETomek": SMOTETomek(),
    "Sampling5_None": None
}

results = []

for samp_name, sampler in sampling_methods.items():
    if sampler:
        X_res, y_res = sampler.fit_resample(X, y)
    else:
        X_res, y_res = X, y

    X_train, X_test, y_train, y_test = train_test_split(
        X_res, y_res, test_size=0.2, random_state=42
    )

    for model_name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred) * 100

        results.append({
            "Model": model_name,
            "Sampling Technique": samp_name,
            "Accuracy (%)": round(acc, 2)
        })

results_df = pd.DataFrame(results)
results_df.to_csv("results.csv", index=False)

print(results_df)